name: app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: 1.1.0
  postgres: ^2.0.0
  intro_views_flutter: ^3.2.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_database: ^10.2.7
  firebase_storage: ^11.2.8
  image_picker: ^1.0.4
  flutter_spinkit: ^5.2.0
  firebase_messaging: ^14.7.9
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  timezone: ^0.9.2
  introduction_screen: ^3.1.12
  showcaseview: ^2.0.3
  flutter_email_sender: ^5.0.2
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.0
  awesome_notifications_core: ^0.8.0 # <~ always ensure to use the latest version
  awesome_notifications: 
  mailer: ^6.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagens/labmaker-logo.jpg
    - assets/imagens/labmaker-splash.png
    - assets/imagens/labmaker-navbar2.jpg
    - assets/imagens/arduinokit.jpg
    - assets/imagens/cortadora-laser.jpg
    - assets/imagens/CR5proh.jpg
    - assets/imagens/impressora3d.png
    - assets/imagens/arduino.png
    - assets/imagens/grmax5.jpg
    - assets/imagens/ferro-de-solda.png
    - assets/imagens/furadeira.jpg
    - assets/imagens/labMaker.jpg
    - assets/imagens/leoCampello.jpg
    - assets/imagens/vicCarlos.jpg
    - assets/imagens/viniEufrazio.jpg
    - assets/imagens/PLemos.jpg
    - assets/imagens/github.png
    - assets/imagens/instagram.png
    - assets/imagens/linkedin.png
    - assets/imagens/felipe.jpg
    - assets/imagens/adeisa-guimaraes.jpeg
    - assets/imagens/augusto-coimbra.jpeg
    - assets/imagens/francenila-rodrigues.jpeg
    - assets/imagens/francisco-kelsen.jpeg
    - assets/imagens/handherson-damasceno.jpeg
    - assets/imagens/marcelo-santos.jpeg
    - assets/imagens/marcelo-souza.jpeg
    - assets/imagens/marcos-padilha.jpeg
    - assets/imagens/marinaldo.jpeg
    - assets/imagens/pedro-davi.jpeg
    - assets/imagens/thales-ferreira.jpeg
    - assets/imagens/yanne-andrade.jpeg
    - assets/imagens/alanny.jpg






